### ISSUE TITLE
Support for counts

### ISSUE THREAD

**Issue by blueyed** [breuckelen/vim-resize#1]
I've came across this plugin when trying to resize a window in a certain direction.

It would be nice if the functions would have support for a count, to make resizing by e.g. 5 lines/columns more efficient.

**Comment by benattal** [comment]
Hey Dan, first of all thanks for using the plugin! 

up / down / left / right resize commands can now be invoked with a number preceding the direction, in order to resize <n> columns or rows. The most recent resize amount is also cached, and used until a new one is specified.

**Comment by blueyed** [comment]
Thanks!
